### ISSUE TITLE
CUDA out of memory error when executing in Google Colab

### ISSUE THREAD

**Issue by VinulaUthsara** [yuesongtian/AlphaGAN#4]
The following CUDA  out of memory occurs when executing the search code

 "CUDA_VISIBLE_DEVICES=0 python search.py --gen Network_gen_Auto --dis Discriminator --gf_dim 256 --df_dim 128 --fix_alphas_epochs -1 --only_update_w_g --gen_normal_opr PRIMITIVES_NORMAL_GEN_wo_skip_none_sep --inner_steps 20 --worst_steps 20 --outter_steps 20 --exp_name search_test  --eval_every 4 --dataset cifar10"

and gives following error:

" RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 15.90 GiB total capacity; 14.84 GiB already allocated; 55.06 MiB free; 15.03 GiB reserved in total by PyTorch) "

Related issue found:

https://github.com/pytorch/pytorch/issues/16417

This is probably due to the large batch size of data being passed to the GPU.

Please let me know how this can be resolved (or how to reduce the batch size).

**Comment by yuesongtian** [comment]
Hi, thank you for trying alphaGAN. 

In cfg_search.py, you can see ``batch_size`` parameter, set to 64 by default. Add ``--batch_size 32`` in your command. Try if this works.

Thank you.

**Comment by VinulaUthsara** [comment]
This still did not resolve the issue. I tried changing the batch size values of 

parser.add_argument('--batch_size', type=int, default=32, help='batch size')
parser.add_argument('-gen_bs', '--gen_batch_size', type=int, default=32, help='size of the batches')
parser.add_argument('-dis_bs', '--dis_batch_size', type=int, default=32, help='size of the batches')

cfg_search.py to 32 which made it run but gives error :  

Traceback (most recent call last):
  File "search.py", line 245, in <module>
    main() 
  File "search.py", line 219, in main
    inception_score, std, fid_score = validate(args, fixed_z, fid_stat, gen, writer_dict, path_helper)
  File "/content/AlphaGAN/functions.py", line 688, in validate
    img_grid = make_grid(sample_imgs, nrow=5, normalize=True, scale_each=True)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/utils.py", line 75, in make_grid
    norm_range(t, range)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/utils.py", line 71, in norm_range
    norm_ip(t, float(t.min()), float(t.max()))
  File "/usr/local/lib/python3.6/dist-packages/torchvision/utils.py", line 64, in norm_ip
    img.clamp_(min=min, max=max)
RuntimeError: Output 0 of UnbindBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
